### ISSUE TITLE
Wrong issue tracker

### ISSUE THREAD

**Issue by eserte** [autarch/Exception-Class#3]
The issues link on https://metacpan.org/release/DROLSKY/Exception-Class-1.39 leads to http://rt.cpan.org/Public/Dist/Display.html?Name=Test-Bits which is probably wrong. Possible reason:
https://metacpan.org/source/DROLSKY/Exception-Class-1.39/dist.ini#L9

**Comment by autarch** [comment]
Thanks! I just uploaded a new release to fix this.
